/**
 * seed-curated-recipes.ts
 *
 * One-time script to seed the 48 curated recipes from mocks/discover.ts
 * into the Supabase `recipes`, `recipe_ingredients`, and `recipe_method_steps` tables.
 *
 * Run with:
 *   SUPABASE_URL=https://... SUPABASE_SERVICE_ROLE_KEY=... npx tsx scripts/seed-curated-recipes.ts
 *
 * Or via MCP (the SQL output is also written to scripts/seed-output.sql).
 */

import { DISCOVER_MEALS } from '../mocks/discover';

// ── Map mock DiscoverMeal → SQL rows ─────────────────────────────────────────

function escape(s: string | undefined | null): string {
  if (s == null) return 'NULL';
  return `'${s.replace(/'/g, "''")}'`;
}

function escapeArray(arr: string[] | undefined | null): string {
  if (!arr || arr.length === 0) return "'{}'";
  const items = arr.map(s => `"${s.replace(/"/g, '\\"')}"`).join(',');
  return `'{${items}}'`;
}

function num(n: number | undefined | null): string {
  if (n == null) return 'NULL';
  return String(n);
}

function bool(b: boolean | undefined | null): string {
  if (b == null) return 'FALSE';
  return b ? 'TRUE' : 'FALSE';
}

// Use a deterministic UUID v5-style mapping: just use a fixed namespace prefix
// so re-running the script produces the same IDs (idempotent).
function deterministicUuid(seed: string): string {
  // Simple deterministic ID based on the mock ID: pad to UUID format
  // disc_1 → 00000000-0000-0000-0000-000000000001
  const num = seed.replace('disc_', '').padStart(12, '0');
  return `00000000-disc-feed-cafe-${num}`;
}

const recipeRows: string[] = [];
const ingredientRows: string[] = [];
const stepRows: string[] = [];

for (const meal of DISCOVER_MEALS) {
  const recipeId = deterministicUuid(meal.id);

  // ── recipes row ────────────────────────────────────────────────────────────
  recipeRows.push(`(
    '${recipeId}',
    NULL,
    ${escape(meal.name)},
    'curated',
    FALSE,
    ${num(meal.recipe_serving_size)},
    ${escapeArray(meal.dietary_tags)},
    '{}',
    0,
    TRUE,
    TRUE,
    ${escape(meal.image_url)},
    ${escape(meal.description)},
    ${escape(meal.cuisine)},
    ${escapeArray(meal.cuisines as string[])},
    ${escape(meal.meal_type)},
    ${escape(meal.cooking_time_band)},
    ${num(meal.prep_time)},
    ${num(meal.cook_time)},
    ${escape(meal.dish_category)},
    ${escape(meal.protein_source)},
    ${escapeArray(meal.occasions)},
    ${bool(meal.is_vegan)},
    ${bool(meal.is_vegetarian)},
    ${bool(meal.is_gluten_free)},
    ${bool(meal.is_dairy_free)},
    ${escapeArray(meal.allergens)},
    ${escapeArray(meal.diet_labels)},
    ${num(meal.taste_sweetness)},
    ${num(meal.taste_saltiness)},
    ${num(meal.taste_sourness)},
    ${num(meal.taste_bitterness)},
    ${num(meal.taste_savoriness)},
    ${num(meal.taste_fattiness)},
    ${num(meal.taste_spiciness)},
    ${num(meal.calories_per_serving)},
    ${num(meal.protein_per_serving_g)},
    ${num(meal.carbs_per_serving_g)},
    ${num(meal.health_score)},
    NOW(),
    NOW()
  )`);

  // ── recipe_ingredients rows ────────────────────────────────────────────────
  if (meal.ingredients) {
    meal.ingredients.forEach((ing, idx) => {
      const ingId = deterministicUuid(`${meal.id}_ing_${idx}`).replace('cafe-', 'cafe-').replace('00000000-disc-feed-cafe-', `${String(idx).padStart(3, '0')}00000-disc-feed-cafe-`);
      ingredientRows.push(`(
        gen_random_uuid(),
        '${recipeId}',
        NULL,
        ${escape(ing.name)},
        ${num(ing.quantity)},
        ${escape(ing.unit)},
        ${escape(ing.category)},
        ${idx}
      )`);
    });
  }

  // ── recipe_method_steps rows ───────────────────────────────────────────────
  if (meal.method_steps) {
    meal.method_steps.forEach((step, idx) => {
      stepRows.push(`(
        gen_random_uuid(),
        '${recipeId}',
        NULL,
        ${escape(step)},
        ${idx}
      )`);
    });
  }
}

// ── Build final SQL ──────────────────────────────────────────────────────────

const sql = `-- Seed: 48 curated Discover recipes
-- Generated by scripts/seed-curated-recipes.ts
-- Safe to re-run (ON CONFLICT DO NOTHING)

INSERT INTO recipes (
  id, family_id, name, source, is_customized, recipe_serving_size,
  dietary_tags, custom_tags, add_to_plan_count, is_ingredient_complete,
  is_recipe_complete, image_url, description, cuisine, cuisines,
  meal_type, cooking_time_band, prep_time, cook_time, dish_category,
  protein_source, occasions, is_vegan, is_vegetarian, is_gluten_free,
  is_dairy_free, allergens, diet_labels,
  taste_sweetness, taste_saltiness, taste_sourness, taste_bitterness,
  taste_savoriness, taste_fattiness, taste_spiciness,
  calories_per_serving, protein_per_serving_g, carbs_per_serving_g,
  health_score, created_at, updated_at
) VALUES
${recipeRows.join(',\n')}
ON CONFLICT (id) DO NOTHING;

INSERT INTO recipe_ingredients (
  id, recipe_id, family_id, name, quantity, unit, category, position
) VALUES
${ingredientRows.join(',\n')}
ON CONFLICT (id) DO NOTHING;

INSERT INTO recipe_method_steps (
  id, recipe_id, family_id, step_text, position
) VALUES
${stepRows.join(',\n')}
ON CONFLICT (id) DO NOTHING;
`;

// Write SQL to file for inspection / MCP execution
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, 'seed-output.sql');
writeFileSync(outPath, sql, 'utf8');

console.log(`✅ SQL written to ${outPath}`);
console.log(`   Recipes:     ${recipeRows.length}`);
console.log(`   Ingredients: ${ingredientRows.length}`);
console.log(`   Steps:       ${stepRows.length}`);
